# Generated by Django 5.2.1 on 2025-06-05 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_attachments/')),
                ('publish_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('academic', 'Academic Updates'), ('exams', 'Examinations & Results'), ('events', 'Events & Celebrations'), ('sports', 'Sports & Games'), ('meetings', 'School Meetings'), ('holidays', 'Holidays & Schedules'), ('fees', 'Fee & Payment'), ('health', 'Health & Safety'), ('ict', 'ICT & e-Learning'), ('workshops', 'Workshops & Seminars'), ('competitions', 'Competitions')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
