# Generated by Django 5.2.1 on 2025-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Updates'), ('exams', 'Examinations & Results'), ('events', 'Events & Celebrations'), ('sports', 'Sports & Games'), ('achievements', 'Student Achievements'), ('meetings', 'School Meetings'), ('holidays', 'Holidays & Schedules'), ('fees', 'Fee & Payment'), ('health', 'Health & Safety'), ('ict', 'ICT & e-Learning'), ('workshops', 'Workshops & Seminars'), ('competitions', 'Competitions')], max_length=20),
        ),
    ]
