# Generated by Django 5.2.1 on 2025-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_news_options_news_slug_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
