# Generated by Django 5.2.1 on 2025-06-12 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('program_type', models.CharField(choices=[('ACAD', 'Academic'), ('SPRT', 'Sports'), ('CULT', 'Cultural'), ('MTNG', 'Meeting'), ('OTHR', 'Other')], max_length=4)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('icon_class', models.CharField(default='fas fa-calendar-day', max_length=50)),
            ],
            options={
                'verbose_name': 'Weekly Program',
                'verbose_name_plural': 'Weekly Programs',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
