# Generated by Django 5.2.1 on 2025-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Sports Day, Debate, etc.', max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('icon', models.CharField(choices=[('fas fa-running', 'Sports'), ('fas fa-comments', 'Debate'), ('fas fa-broom', 'Cleanliness'), ('fas fa-leaf', 'Shamba'), ('fas fa-praying-hands', 'Service & Prayer'), ('fas fa-trophy', 'Weekend Challenge'), ('fas fa-users', 'School Baraza'), ('fas fa-handshake', 'Parent-Teacher Meeting'), ('fas fa-door-open', 'Welcoming Guests'), ('fas fa-music', 'Entertainment')], default='fas fa-calendar-day', max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Weekly Program',
                'verbose_name_plural': 'Weekly Programs',
                'ordering': ['display_order', 'day'],
            },
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
