# Generated by Django 5.2.1 on 2025-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_weeklyprogram_delete_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogram',
            name='icon_color',
            field=models.CharField(choices=[('text-primary', 'Blue'), ('text-success', 'Green'), ('text-danger', 'Red'), ('text-warning', 'Yellow'), ('text-info', 'Cyan'), ('text-secondary', 'Gray'), ('text-dark', 'Black')], default='text-primary', help_text='Color for the program icon', max_length=20),
        ),
    ]
