# Generated by Django 5.2.1 on 2025-06-19 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_weeklyprogram_icon_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2025, unique=True)),
                ('teachers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('form_one', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Form 1 Students')),
                ('form_two', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Form 2 Students')),
                ('form_three', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Form 3 Students')),
                ('form_four', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Form 4 Students')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'School Statistics',
                'ordering': ['-year'],
            },
        ),
    ]
