# Generated by Django 5.2.1 on 2025-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_title', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prayer_date', models.DateField()),
            ],
            options={
                'ordering': ['prayer_date'],
            },
        ),
    ]
