# Generated by Django 5.2.1 on 2025-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='scripture_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
