# Generated by Django 5.2.1 on 2025-07-10 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_prayer_scripture_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='publications/%Y/%m/%d/')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured to highlight this publication')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this publication from public view')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
