# Generated by Django 5.2.1 on 2025-07-12 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title for the image', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Detailed description of the image (shown in popups)')),
                ('image', models.ImageField(help_text='Upload high-quality school images', upload_to='gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images appear in the homepage slideshow')),
                ('date_taken', models.DateField(blank=True, help_text='When was this photo taken? (optional)', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', '-upload_date'],
            },
        ),
    ]
