# Generated by Django 5.2.1 on 2025-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_about',
            field=models.BooleanField(default=False, help_text='Set to true if this image is used in the About Us section'),
        ),
    ]
